
name: attacker server
on:
  push:
    branches: [main]
    paths:
      - "AttackServer/**"

jobs:
  integrate:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: docker login -u ${{secrets.USERNAME_CANISTER}} -p ${{secrets.PASSWORD_CANISTER}} cloud.canister.io:5000
      - run: cd AttackServer && docker build -t "cloud.canister.io:5000/msmarcks/csrfattackserver:latest" .
      - run: docker push cloud.canister.io:5000/msmarcks/csrfattackserver:latest